name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-common:
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    env:
      MONGODB_VERSION: 3.6.9
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile

      - run: yarn run lint
      - run: yarn run test
        env:
          CI: true


